name: Issue Asigned

on:
  issues:
    types:
      - assigned
  

jobs:
  issue_asigned:
    runs-on: ubuntu-20.04
    steps:
      - name: "echo the action"
        run: echo '${{ github.actor }}' se ha '${{ github.event_name }}'
  